Trezanik MemMgr (C): tracked_memory.h File Reference
tracked_memory.h File Reference
Memory Allocation tracking for the application.
#include <sys/queue.h>
#include <pthread.h>
#include <inttypes.h>
#include <stdbool.h>
Data Structures
struct memblock_footer
struct memblock_header
struct mem_context
Macros
#define USING_MEMORY_DEBUGGING
#define DISABLE_MEMORY_CHECK_TO_STDOUT
#define DISABLE_MEMORY_OP_TO_STDOUT
#define __STDC_FORMAT_MACROS
#define MEM_LEAK_LOG_NAME "memdynamic.log"
#define MEM_MAX_FILENAME_LENGTH 31
#define MEM_MAX_FUNCTION_LENGTH 31
#define PRINT_POINTER "%08" PRIxPTR
#define MALLOC(size) tracked_alloc(&g_mem_ctx, size, __FILE__, __FUNCTION__, __LINE__)
#define REALLOC(ptr, size) tracked_realloc(&g_mem_ctx, ptr, size, __FILE__, __FUNCTION__, __LINE__)
#define FREE(varname) tracked_free(&g_mem_ctx, varname)
#define MEM_OUTPUT_LIMIT 1024
Enumerations
enum E_MEMORY_ERROR {
EC_NoError = 0, EC_NoMemoryBlock, EC_CorruptHeader, EC_CorruptFooter,
EC_SizeMismatch
}
Functions
enum E_MEMORY_ERROR check_block (struct memblock_header *memory_block)
void mem_context_destroy (struct mem_context *const context)
void mem_context_init (struct mem_context *const context)
void output_memory_info (struct mem_context *const context)
void * tracked_alloc (struct mem_context *const context, const uint32_t num_bytes, const char *file, const char *function, const uint32_t line)
void tracked_free (struct mem_context *const context, void *memory)
void * tracked_realloc (struct mem_context *const context, void *memory, const uint32_t new_num_bytes, const char *file, const char *function, const uint32_t line)
bool validate_memory (struct mem_context *const context, void *memory)
Variables
struct mem_context g_mem_ctx
Detailed Description
Memory Allocation tracking for the application.
Author
James Warren
Definition in file tracked_memory.h.
Macro Definition Documentation
#define __STDC_FORMAT_MACROS
Definition at line 30 of file tracked_memory.h.
#define DISABLE_MEMORY_CHECK_TO_STDOUT
Definition at line 15 of file tracked_memory.h.
#define DISABLE_MEMORY_OP_TO_STDOUT
Definition at line 16 of file tracked_memory.h.
#define FREE (varname) tracked_free(&g_mem_ctx, varname)
Macro to delete tracked memory
Definition at line 351 of file tracked_memory.h.
Referenced by main().
#define MALLOC (size) tracked_alloc(&g_mem_ctx, size, __FILE__, __FUNCTION__, __LINE__)
Macro to create tracked memory
Definition at line 345 of file tracked_memory.h.
Referenced by main().
#define MEM_LEAK_LOG_NAME "memdynamic.log"
Definition at line 36 of file tracked_memory.h.
Referenced by mem_context_destroy(), and output_memory_info().
#define MEM_MAX_FILENAME_LENGTH 31
Definition at line 37 of file tracked_memory.h.
#define MEM_MAX_FUNCTION_LENGTH 31
Definition at line 38 of file tracked_memory.h.
#define MEM_OUTPUT_LIMIT 1024
The amount of bytes (limit) printed to output under the Data field
Definition at line 354 of file tracked_memory.h.
Referenced by output_memory_info().
#define PRINT_POINTER "%08" PRIxPTR
Definition at line 50 of file tracked_memory.h.
Referenced by output_memory_info().
#define REALLOC (ptr, size) tracked_realloc(&g_mem_ctx, ptr, size, __FILE__, __FUNCTION__, __LINE__)
Macro to reallocate tracked memory
Definition at line 348 of file tracked_memory.h.
#define USING_MEMORY_DEBUGGING
Definition at line 14 of file tracked_memory.h.
Enumeration Type Documentation
enum E_MEMORY_ERROR
Memory-specific error codes. Used only as the return value from check_block().
Enumerator
EC_NoError
EC_NoMemoryBlock
EC_CorruptHeader
EC_CorruptFooter
EC_SizeMismatch
Definition at line 114 of file tracked_memory.h.
 {
         EC_NoError = 0,
         EC_NoMemoryBlock,
         EC_CorruptHeader,
         EC_CorruptFooter,
         EC_SizeMismatch
 };
Function Documentation
enum E_MEMORY_ERROR check_block (struct memblock_header * memory_block)
Checks a block of memory, ensuring both the header and footer are not corrupt, and the rest of the block matches the original requestors specifications.
Define DISABLE_MEMORY_CHECK_TO_STDOUT to prevent stage-by-stage output of the checking process.
Parameters
[in] memory_block The block of memory to check
Return values
E_MEMORY_ERROR The relevant memory error code as to the block status; should hopefully always be EC_NoError
Definition at line 92 of file tracked_memory.c.
References EC_CorruptFooter, EC_CorruptHeader, EC_NoError, EC_NoMemoryBlock, EC_SizeMismatch, memblock_header::file, memblock_header::footer, memblock_header::line, memblock_footer::magic, memblock_header::magic, mem_footer_magic, mem_header_magic, memblock_header::real_size, and memblock_header::requested_size.
Referenced by output_memory_info(), and validate_memory().
 {
         uint32_t        block_size = 0;
         if ( memory_block == NULL )
                 goto null_block;
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\tChecking Memory Block %p..\n",
                 memory_block);
         printf("\t\tGlobal Header magic number is %lu bytes in size :: %#x\n",
                 sizeof(mem_header_magic), mem_header_magic);
         printf("\t\tGlobal Footer magic number is %lu bytes in size :: %#x\n",
                 sizeof(mem_footer_magic), mem_footer_magic);
 #endif
         if ( memcmp(&memory_block->magic,
                 &mem_header_magic,
                 sizeof(mem_header_magic)) != 0 )
         {
                 /* memory_block magic number has been modified; block contents
                  * are unstable */
                 goto corrupt_header;
         }
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tHas a valid header (%lu bytes, %#x)...\n",
                 sizeof(memory_block->magic), memory_block->magic);
         printf("\t\tHeader Info:: %u (%u requested) bytes, line %u in %s\n",
                 memory_block->real_size, memory_block->requested_size,
                 memory_block->line, memory_block->file);
 #endif
         if ( memory_block->footer == NULL ||
                 memcmp(&memory_block->footer->magic, &mem_footer_magic, sizeof(mem_footer_magic)) != 0 )
         {
                 /* memory_block footer magic has been modified - as the header
                  * is not corrupt, we can retrieve the allocation info safely */
                 goto corrupt_footer;
         }
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tHas a valid footer (%lu bytes, %#x)...\n",
                 sizeof(memory_block->footer->magic),
                 memory_block->footer->magic);
 #endif
         // calculate the size requested by removing the header + footer
         block_size = ((uint8_t*)memory_block->footer) - ((uint8_t*)memory_block + sizeof(struct memblock_header));
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tCalculated block_size is %u bytes\n", block_size);
 #endif
         if ( memory_block->requested_size != block_size )
         {
                 /* The size stored by the memory_block header is different from
                  * that calculated (remember we've already validated the magic
                  * numbers) */
                 goto invalid_size;
         }
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tHas a valid app_mem size (%u bytes)\n\t\tValidated!\n",
                block_size);
 #endif
         // memory_block is as expected
         return EC_NoError;
 null_block:
         // Optional: Raise error
         return EC_NoMemoryBlock;
 corrupt_header:
         // Optional: Raise error
         return EC_CorruptHeader;
 corrupt_footer:
         // Optional: Raise error
         return EC_CorruptFooter;
 invalid_size:
         // Optional: Raise error
         return EC_SizeMismatch;
 }
void mem_context_destroy (struct mem_context *const context)
Destroys a previously initialized memory context. If any memory blocks exist within the list, it is declared as a memory leak, and will call the output_memory_info() function to report it.
Parameters
[in] context The memory context to destroy
Definition at line 74 of file tracked_memory.c.
References mem_context::lock, MEM_LEAK_LOG_NAME, output_memory_info(), and TAILQ_EMPTY.
Referenced by main().
 {
         if ( !TAILQ_EMPTY(&context->memblocks) )
         {
                 printf("Memory Leak Detected\n\nCheck '%s' for details\n",
                        MEM_LEAK_LOG_NAME);
         }
         output_memory_info(context);
         pthread_mutex_destroy(&context->lock);
 }
void mem_context_init (struct mem_context *const context)
Initializes the memory context, ready for usage.
Must be destroyed via mem_context_destroy().
Parameters
[in] context The memory context to initialize
Definition at line 55 of file tracked_memory.c.
References mem_context::allocs, mem_context::current_allocated, mem_context::frees, mem_context::lock, mem_context::lock_attrib, TAILQ_INIT, and mem_context::total_allocated.
Referenced by main().
 {
         pthread_mutexattr_settype(&context->lock_attrib, PTHREAD_MUTEX_RECURSIVE);
         pthread_mutexattr_settype(&context->lock_attrib, PTHREAD_PROCESS_PRIVATE);
         pthread_mutex_init(&context->lock, &context->lock_attrib);
         context->allocs                 = 0;
         context->frees                  = 0;
         context->current_allocated      = 0;
         context->total_allocated        = 0;
         TAILQ_INIT(&context->memblocks);
 }
void output_memory_info (struct mem_context *const context)
Called only in the destructor, but available for calling manually if desired; will always output the memory stats for the application run, but will also write out the information on any unfreed memory.
Outputs to MEM_LEAK_LOG_NAME, but if it's not writable, it is printed to stderr instead.
Parameters
[in] context The memory context to work with
Todo:
causes warning 'cast to pointer from integer of different size' and 'format x expects argument of type unsigned int'
Definition at line 182 of file tracked_memory.c.
References mem_context::allocs, block_offset_realmem, check_block(), mem_context::current_allocated, EC_CorruptFooter, EC_CorruptHeader, EC_NoError, EC_NoMemoryBlock, EC_SizeMismatch, mem_context::frees, HEADER_FOOTER_SIZE, MEM_LEAK_LOG_NAME, MEM_OUTPUT_LIMIT, PRINT_POINTER, TAILQ_FOREACH, TAILQ_REMOVE, and mem_context::total_allocated.
Referenced by mem_context_destroy().
 {
         enum E_MEMORY_ERROR     result;
         struct memblock_header* block_ptr;
         FILE*           leak_file;
         int32_t         close_file = 1;
         uint32_t        i = 0;
         // we don't store/track the user-requested amounts, only the real
         uint32_t        requested_alloc;
         uint32_t        requested_unfreed;
         /* since Windows has been kind enough to not provide more standards
          * complaint security functionality, we shall have to use their own
          * fopen_s. POSIX builds can happily use the 'x' flag to provide a
          * decent security level - fopen_s is still vulnerable to potential
          * exploits ironically... */
 #if defined(_WIN32)
         if ( fopen_s(&leak_file, MEM_LEAK_LOG_NAME, "w+") != 0 )
         {
 #else
         if (( leak_file = fopen(MEM_LEAK_LOG_NAME, "w+")) == NULL )
         {
 #endif
                 leak_file = stdout;
                 close_file = 0;
         }
         /* Remove memory block sizes, multiplied by the number of allocations,
          * which is taken away from the total amount allocated. */
         requested_alloc         = context->total_allocated - (HEADER_FOOTER_SIZE * context->allocs);
         /* Remove memory block sizes, multiplied by the number of pending frees,
          * which is to be taken away from the current amount still allocated. */
         requested_unfreed       = context->current_allocated - (HEADER_FOOTER_SIZE * (context->allocs - context->frees));
         fprintf(leak_file,
                 "# Details\n"
                 "Header+Footer Size......: %lu\n"
                 "\n"
                 "# Code Stats\n"
                 "Allocations.............: %u\n"
                 "Frees...................: %u\n"
                 "Pending Frees...........: %u\n"
                 "\n"
                 "# Totals, Real\n"
                 "Bytes Allocated.........: %u\n"
                 "Unfreed Bytes...........: %u\n"
                 "\n"
                 "# Totals, Requested\n"
                 "Bytes Allocated.........: %u\n"
                 "Unfreed Bytes...........: %u\n"
                 "\n"
                 "##################\n"
                 "  Unfreed Blocks  \n",
                 HEADER_FOOTER_SIZE,
                 context->allocs, context->frees, (context->allocs - context->frees),
                 context->total_allocated, context->current_allocated,
                 requested_alloc, requested_unfreed
                 );
         TAILQ_FOREACH(block_ptr, &context->memblocks, np_blocks)
         {
                 i++;
                 fprintf(leak_file,
                         "##################\n"
                         "%u)\n"
                         "Block...: " PRINT_POINTER
                         "\n",
                         i, (uintptr_t)block_ptr
                 );
                 result = check_block(block_ptr);
                 switch ( result )
                 {
                 case EC_NoMemoryBlock:
{
                                 fprintf(leak_file,
                                         "Error...: Block Pointer was NULL\n"
                                 );
                                 break;
                         }
                 case EC_CorruptFooter:
{
                                 fprintf(leak_file,
                                         "Error...: Corrupt Footer\n"
                                 );
                                 break;
                         }
                 case EC_CorruptHeader:
{
                                 fprintf(leak_file,
                                         "Error...: Corrupt Header\n"
                                 );
                                 break;
                         }
                 case EC_SizeMismatch:
{
                                 fprintf(leak_file,
                                         "Error...: Size Mismatch (%u actual bytes)\n",
                                         block_ptr->requested_size
                                 );
                                 break;
                         }
                 case EC_NoError:
                 default:
                         break;
                 }
                 /* can't fall through in switch, so have to do a secondary check
                  * as we can't print data that's corrupt or a NULL */
                 if ( result != EC_NoMemoryBlock && result != EC_CorruptHeader )
                 {
                         fprintf(leak_file,
                                 "Size....: %u\n"
                                 "Function: %s\n"
                                 "File....: %s\n"
                                 "Line....: %u\n",
                                 block_ptr->requested_size,
                                 block_ptr->function,
                                 block_ptr->file,
                                 block_ptr->line
                         );
                         fprintf(leak_file, "Data....: ");
                         for ( uint32_t j = 0;
                                 j < block_ptr->requested_size && j < MEM_OUTPUT_LIMIT;
                                 j++ )
{
                                 fprintf(leak_file,
                                         "%02x ",
                                         block_offset_realmem(block_ptr)[j]);
                         }
                         fprintf(leak_file, "\n");
                 }
         }
         if ( close_file )
                 fclose(leak_file);
         /* try to free whatever we didn't during runtime; if any of these are
          * screwed (heap corruption) then this will probably trigger a crash */
         TAILQ_FOREACH(block_ptr, &context->memblocks, np_blocks)
         {
                 TAILQ_REMOVE(&context->memblocks, block_ptr, np_blocks);
                 free(block_ptr);
         }
 }
void* tracked_alloc (struct mem_context *const context, const uint32_t num_bytes, const char * file, const char * function, const uint32_t line)
Tracked version of malloc - use the MALLOC macro to call this, as it will setup the parameters for you, barring the num_bytes.
This function will dynamically alter the requested amount in order to leave space for a header and footer; the client code does not need to handle, or be aware, of this fact.
Parameters
[in] context The memory context to work with
[in] num_bytes The number of bytes to allocate
[in] file The file this method was called in
[in] function The function this method was called in
[in] line The line number in the file this method was called in
Returns
A pointer to the allocated memory, or a nullptr if the allocation failed.
Definition at line 337 of file tracked_memory.c.
References mem_context::allocs, block_offset_footer, block_offset_realmem, mem_context::current_allocated, memblock_header::file, memblock_header::footer, memblock_header::function, HEADER_FOOTER_SIZE, memblock_header::line, mem_context::lock, memblock_footer::magic, memblock_header::magic, mem_footer_magic, mem_header_magic, MEM_ON_INIT, PATH_CHAR, memblock_header::real_size, memblock_header::requested_size, TAILQ_INSERT_TAIL, and mem_context::total_allocated.
Referenced by tracked_realloc().
 {
         struct memblock_header* mem_block = NULL;
         struct memblock_footer* mem_footer = NULL;
         void*                   mem_return = NULL;
         char*                   p = NULL;
         uint32_t                patched_alloc = 0;      // num_bytes + memblocks
         // allocate the requested amount, plus the size of the header & footer memblocks
         patched_alloc = num_bytes + HEADER_FOOTER_SIZE;
         // the actual, real, physical allocation of memory
         mem_block = (struct memblock_header*)malloc(patched_alloc);
         if ( mem_block == NULL )
                 goto alloc_failure;
         // initialize the value for the new memory
         memset(mem_block, MEM_ON_INIT, patched_alloc);
 #if defined(_WIN32)
 #       define PATH_CHAR        '\\'
 #else
 #       define PATH_CHAR        '/'
 #endif
         // we don't want the full path information that compilers set
         if (( p = strrchr(file, PATH_CHAR)) != NULL )
                 file = ++p;
         // calculate the offsets of the return memory and the footer
         mem_return = block_offset_realmem(mem_block);
         mem_footer = block_offset_footer(mem_block, num_bytes);
         // prepare the structure internals
         mem_footer->magic       = mem_footer_magic;
         mem_block->footer       = mem_footer;
         mem_block->magic        = mem_header_magic;
         mem_block->line         = line;
         mem_block->real_size            = patched_alloc;
         mem_block->requested_size       = num_bytes;
         /* you should be using strlcpy if you're doing character buffer copying
          * and other functionality!! For the sake of securing your application,
          * please USE IT!
          * We provide a 'normal, well-known' alternative for the sake of the
          * example using strncpy (which is in standard headers everywhere) */
 #if defined(HAVE_STRLCPY)
         strlcpy(mem_block->file, file, sizeof(mem_block->file));
         strlcpy(mem_block->function, function, sizeof(mem_block->function));
 #else
         strncpy(mem_block->file, file, sizeof(mem_block->file)-1);
         strncpy(mem_block->function, function, sizeof(mem_block->function)-1);
 #endif
         /* lock this context, only 1 thread to update sensitive internals at a
          * time - lock for as little time as possible! */
         pthread_mutex_lock(&context->lock);
         // update the stats, using patched values
         context->allocs++;
         context->current_allocated += patched_alloc;
         context->total_allocated += patched_alloc;
         // append it to the list
         TAILQ_INSERT_TAIL(&context->memblocks, mem_block, np_blocks);
         // unlock the context, other threads can now allocate from this class
         pthread_mutex_unlock(&context->lock);
         return mem_return;
 alloc_failure:
         return NULL;
 }
void tracked_free (struct mem_context *const context, void * memory)
Tracked version of free - use the FREE macro to call this, for consistency and potential future changes.
In compliance with the C standard, if memory is a nullptr, this function performs no action. No action is also performed if a memory validation check fails (i.e. the supplied block is corrupt or otherwise invalid), as doing so could crash the application, and miss logging the information.
Parameters
[in] context The memory context to work with
[in] memory A pointer to the memory previously allocated by tracked_alloc (which should be called via MALLOC)
Definition at line 420 of file tracked_memory.c.
References block_offset_header, mem_context::current_allocated, memblock_header::file, mem_context::frees, memblock_header::line, mem_context::lock, MEM_AFTER_FREE, memblock_header::real_size, memblock_header::requested_size, TAILQ_REMOVE, and validate_memory().
Referenced by tracked_realloc().
 {
         struct memblock_header* mem_block = NULL;
         // as per the C standard, if it's a NULL, do nothing
         if ( memory == NULL )
                 return;
         if ( !validate_memory(context, memory) )
                 return;
         mem_block = block_offset_header(memory);
 #if !defined(DISABLE_MEMORY_OP_TO_STDOUT)
         printf( "free [%s (%u bytes) line %u]\n"
                 "\tBlock: %p | Usable Block: %p\n",
                 mem_block->file, mem_block->requested_size, mem_block->line,
                 mem_block, memory);
 #endif
         // stop other modifications on this memory context
         pthread_mutex_lock(&context->lock);
         // update the context stats
         context->frees++;
         context->current_allocated -= (mem_block->real_size);
         // remove the mem_block from the list
         TAILQ_REMOVE(&context->memblocks, mem_block, np_blocks);
         // we're done with the class internals, open it up again
         pthread_mutex_unlock(&context->lock);
         // fill the app-allocated memory (highlights use after free)
         memset(mem_block, MEM_AFTER_FREE, mem_block->real_size);
         // perform the actual freeing of memory, including our header + footer
         free(mem_block);
         return;
 }
void* tracked_realloc (struct mem_context *const context, void * memory, const uint32_t new_num_bytes, const char * file, const char * function, const uint32_t line)
Tracked version of realloc - use the REALLOC macro to call this.
In compliance with the C standard, if memory_block is a nullptr, the end result is the same as calling tracked_alloc (i.e. malloc). The same applies if new_num_bytes is 0 - tracked_free (i.e. free) will be called on the memory block.
No validation is performed on the original block of memory, and unlike the real realloc, we call TrackedAlloc regardless of size differences and other parameters. The previous memory is then moved into this newly allocated block, and the original freed.
As a result, a TrackedRealloc guarantees that the returned pointer will never be the same as the one passed in.
Parameters
[in] context The memory context to work with
[in] memory The pointer to memory returned by TrackedAlloc()
[in] new_num_bytes The new number of bytes to allocate
[in] file The file this method was called in
[in] function The function this method was called in
[in] line The line number in the file this method was called in
Return values
nullptr if the function fails due to invalid parameters, or the call to realloc fails
Returns
A pointer to the usable block of memory allocated
Definition at line 466 of file tracked_memory.c.
References block_offset_header, mem_context::lock, memblock_header::requested_size, tracked_alloc(), and tracked_free().
 {
         struct memblock_header* mem_block = NULL;
         void*                   mem_return = NULL;
         if ( memory == NULL )
         {
                 // if the memory is NULL, call malloc [ISO C]
                 return tracked_alloc(context, new_num_bytes, file, function, line);
         }
         if ( new_num_bytes == 0 )
         {
                 /* if new_num_bytes is 0 and the memory is not null, call
                  * free() [ISO C] */
                 tracked_free(context, memory);
                 /* whether it works or fails, the memory is still unusable, so
                  * return a NULL */
                 return NULL;
         }
         pthread_mutex_lock(&context->lock);
 #if !defined(DISABLE_MEMORY_OP_TO_STDOUT)
         // since we call TrackedAlloc, make the log info accurate
         printf( "realloc [%s (%u bytes) line %u]\n"
                 "\tTo be allocated in the following malloc; using memory at: %p\n",
                 file, new_num_bytes, line,
                 memory);
 #endif
         mem_return = (void*)tracked_alloc(context, new_num_bytes, file, function, line);
         if ( mem_return != NULL )
         {
                 mem_block = block_offset_header(memory);
                 // move the original data into the new allocation
                 mem_block->requested_size < new_num_bytes ?
                         memmove(mem_return, memory, new_num_bytes) :
                         memmove(mem_return, memory, mem_block->requested_size);
                 // free the original block
                 tracked_free(context, memory);
         }
         pthread_mutex_unlock(&context->lock);
         return mem_return;
 }
bool validate_memory (struct mem_context *const context, void * memory)
Validates a tracked bit of memory; if no pointer is supplied, so nullptr is passed in, every tracked block currently present in the class is validated.
If present, the memory passed in must be at the pointer to the memory returned by the tracked_alloc/tracked_realloc caller.
Internally calls check_block().
Parameters
[in] context The mem_context memory resides in
[in] memory A pointer to the memory to validate
Return values
true if the memory is not corrupt and usable
false if the memory failed one of the checks
Definition at line 527 of file tracked_memory.c.
References block_offset_header, check_block(), EC_NoError, mem_context::lock, and TAILQ_FOREACH.
Referenced by tracked_free().
 {
         bool    ret = true;
         struct memblock_header* mem_block;
         pthread_mutex_lock(&context->lock);
         // if no pointer was specified, check the entire list
         if ( memory == NULL )
         {
                 TAILQ_FOREACH(mem_block, &context->memblocks, np_blocks)
                 {
                         // bail if a block is invalid
                         if ( check_block(mem_block) != EC_NoError )
{
                                 ret = false;
                                 break;
                         }
                 }
         }
         else
         {
                 mem_block = block_offset_header(memory);
                 ret = (check_block(mem_block) == EC_NoError);
         }
         pthread_mutex_unlock(&context->lock);
         return ret;
 }
Variable Documentation
struct mem_context g_mem_ctx
The default, global, memory context to use for all memory operations
Definition at line 50 of file tracked_memory.c.
Referenced by main().